; (package-initialize)

(add-to-list 'load-path (expand-file-name "config" user-emacs-directory))

(require 'lf-ui-primary)
(require 'lf-package-setup)

(setq custom-file "~/.emacs.d/customizations.el")
(if (file-exists-p custom-file)
    (load custom-file))

(require 'lf-ui-theme)
(require 'lf-integration-ag)
(require 'lf-integration-helm)
(require 'lf-integration-magit)
(require 'lf-integration-neotree)
(require 'lf-integration-projectile)
(require 'lf-integration-eshell)
(require 'lf-integration-company)
(require 'lf-integration-flycheck)
(require 'lf-integration-yas)
(require 'lf-utils-editing)
(require 'lf-integration-elfeed)
(require 'lf-utils-nav)
(require 'lf-utils-fs)
(require 'lf-lang-ts)
(require 'lf-lang-js)
(require 'lf-lang-misc)
(require 'lf-ide-setup)

(require 'lf-css-to-js)
